### ISSUE TITLE
Validation issue when moving to different records

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Climsoft#119]
I have two records in my form_daily2 table for different element. The first has all values of 9, the second has all values of 33. When I move from first to second record I get 31 validation error messages saying that 9 is the upper limit.

I assume this is because it is still using the validation of the first element as its moving to the second element and so thinks the values of 33 are invalid.

Setting the validation on the text boxes needs to be updated correctly when changing records.

**Comment by Patowhiz** [comment]
@dannyparsons  Which element value / code did you test with? For those validations

**Comment by dannyparsons** [comment]
The element ids for first and second record are 43 and 47 respectively.

**Comment by Patowhiz** [comment]
Yep. True. The setting of validation is being done after setting of values
