### ISSUE TITLE
Which branch should we work with ?

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/Climsoft#14]
@dannyparsons  @volloholic  @maxwellfundi should we start making pull request against the master branch or the dev branch?

**Comment by maxwellfundi** [comment]
@Patowhiz  we should do pull requests to the dev branch. That was our previous agreement. Unless we have a reason to change.

**Comment by Patowhiz** [comment]
I can see you have a pull request #11  First copy of reading and writing from frmNewDaily2 . is your branch with the latest code changes?

**Comment by maxwellfundi** [comment]
yes that has the latest changes from Last week.
