### ISSUE TITLE
Do we want to update all fields on forms when we change view type in Selectors?

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Climsoft#16]
I have realized  in our current selectors, when i change the view type from names to IDs or vice versa, the fields in the form change even when the ID is the equivalent of the station/element name. 
@africanmathsinitiative/climsoft  do you think this is how we want this to work?  @shadrackkibet  @Patowhiz

**Comment by Patowhiz** [comment]
I think the view type shouldn't affect the other controls. It shouldn't
raise our event change and the selected value should be retained

**Comment by dannyparsons** [comment]
That's correct it shouldn't affect linked control or raise events.

**Comment by maxwellfundi** [comment]
This has also been addressed. Closing it
