### ISSUE TITLE
Concerned about the speed at which our controls respond to events

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Climsoft#17]
I am not sure why  forms  seems to be very slow to populate the controls when we change the contents of our selectors. Anyone with ideas how to make this faster? @Patowhiz @shadrackkibet  @dannyparsons , @volloholic

**Comment by Patowhiz** [comment]
It's cause every control is making a separate data call which means our
connection object is querying multiple times to the database.

We just need to manage this at the connection object level. One way is to
have it read from it's cached db table. We can work on this

**Comment by dannyparsons** [comment]
This is now considerably faster after changing the implementation to have only `ucrFormDaily2` reading from the database. Our reading from the database and creating a `DataTable` is still not particularly fast but this can be improved in our data link in future.

**Comment by maxwellfundi** [comment]
This has been fixed. Am closing it
