### ISSUE TITLE
Clear button behaviour

### ISSUE THREAD

**Issue by dannyparsons** [africanmathsinitiative/Climsoft#25]
The clear button on new forms does not seem to be behaving as it does on original forms. Clear effectively cancels the 'Add New' and goes back to the first record. It is only enabled after clicking Add New.

On our new forms it is (worryingly) doing different things on different forms but on none of them is it doing as above. Was it discussed to do this differently?
If not, I have corrected this on the new form2daily (pushing changes soon) but it will need to be done consistently on all forms.

**Comment by Patowhiz** [comment]
@dannyparsons please use frmNewHourlyWind. It's the one that I did a replica of the old form. Form2Daily is being handled by maxwell

**Comment by dannyparsons** [comment]
I checked frmNewHourlyWind as well and it's also doing something different to what I've described above. There's also strange bugs where edited values remain even if I don't save the record, but I may not have the most up to date version of the form.

Although different people work on different forms you should be aware of what each other are doing, especially since the forms very similar things so you should be making sure it is consistent.

**Comment by Patowhiz** [comment]
@dannyparsons  edited values are retained because of the entity framework. Everytime you type something on the textbox it sets the particular entity field. The framework caches these values. One way of solving this is by working with a detached entity, alternatively though I strongly don't advocate it is to force the context object to refresh it's values everytime you go to another record.

**Comment by Patowhiz** [comment]
```
Private Sub btnClear_Click(sender As Object, e As EventArgs) Handles btnClear.Click
        ucrDaiy2Navigation.MoveFirst()
        SaveEnable()
     End Sub
```
From the above code, which is more advisable between going the previous record (the one that was being viewed before the add new ) or just going to the first record.

**Comment by Patowhiz** [comment]
Then on the same clear functionality. This is how we conceptualised the navigation control. When you click on add new, it's navigation buttons get disabled and it's textbox displays new record position. When you save or click on clear, the navigation buttons are enabled(restored). This was to let a user know that he can't go to the next record on operation add new.

If such a functionality is not what's needed I can just delete the subroutine which does that.

**Comment by maxwellfundi** [comment]
The clear on my form too goes to the first record and so am calling MoveFirst() for the navigation control

**Comment by dannyparsons** [comment]
> The clear on my form too goes to the first record and so am calling MoveFirst() for the navigation control

Great, that is how the original forms work so we should start by doing the same. Please communicate with each other so that the things work consistently across dialogs.

**Comment by Patowhiz** [comment]
This is now solved. The remaining part is to ask Samuel as to why it was necessary to check "Incomplete header information" during the clear.

**Comment by Patowhiz** [comment]
This was fixed
