### ISSUE TITLE
Populating element and station selectors with user text

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Climsoft#42]
Having the right click menu is great but Samuel would like the feature where the user is able to type in an element/station  name or ID and its populated onto the station/element selector. 

An additional desirable enhancement would be;- While typing the station/element name, the items of the combo box get sorted to remain with the closest string to what the user is typing.

**Comment by Patowhiz** [comment]
@maxwellfundi I can work on this if you haven't started it.

**Comment by maxwellfundi** [comment]
@Patowhiz  Go ahead

**Comment by Patowhiz** [comment]
@maxwellfundi from your explanation I'm torn between just suggesting or suggesting and appending

cboValues.AutoCompleteMode = AutoCompleteMode.Suggest

or

cboValues.AutoCompleteMode = AutoCompleteMode.SuggestAppend

The first one the user will have to select the suggested items either by mouse or arrow keys, the latter will be highlighting the untyped letters and the user can just press enter or change focus.

@dannyparsons I'm implementing this as the desired default for all our selectors inside the ucrDataLinkCombobox if that's okay with you?
Theres is also 2 ways of doing this, through the designer properties panel or through code. I prefer through code but I'm okay with implementing through the properties panel.

**Comment by Patowhiz** [comment]
The picture below illustrates 

<img width="215" alt="selector" src="https://user-images.githubusercontent.com/21179007/39001130-3a04118e-43fe-11e8-9737-dd660ed034e3.png">
this.

**Comment by maxwellfundi** [comment]
Am reopening this because one thing is missing

We need the user to see the descriptions of the station/element when they type station/element ids.

**Comment by Patowhiz** [comment]
This has now been fixed
