### ISSUE TITLE
Typing into year selector

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Climsoft#43]
Typing in the year selectors throws a bug.

**Comment by maxwellfundi** [comment]
@africanmathsinitiative/developers I dont seem to be able to replicate this error. Please keep testing you might replicate it and find out what the bug is.

**Comment by Patowhiz** [comment]
Checking this

**Comment by Patowhiz** [comment]
The error is thrown when someone types in a letter. Its an InvalidCastException which occurs in SetValue subroutine of the ComboBoxLink parent control. The Items in the year selector or of type Integer and the set value is a string, this breaks the application during runtime. 
I have fixed this.
