### ISSUE TITLE
Saving data for future

### ISSUE THREAD

**Issue by maxwellfundi** [africanmathsinitiative/Climsoft#45]
We should not be able to save data for future. The last acceptable record is usually of the previous day.

**Comment by maxwellfundi** [comment]
@Patowhiz how do you suggest we implement this?

**Comment by Patowhiz** [comment]
@maxwellfundi I don't if this should happen during the save only or even during the selection of month and day. 
During the save we can do this by getting the currently set date from the computer and checking it against year in ucrYear, the month in the `ucrMonth ` and day in the `ucrDay `. If the **user**  combined choice value is greater than the computer's date then the save operation should not be allowed.

**Comment by maxwellfundi** [comment]
So the save should not be disabled, the point is that we should only allow entry until the previous day in these forms. So we need to just disable the current day onwards. 

We could keep checking when the month, year and day is changed and check that value with current date then disable appropriately. Something similar to the leap year thing

**Comment by Patowhiz** [comment]
Just to clarify. Do you mean we should only allow entry upto the previous day **NOT** upto the current day?

**Comment by Patowhiz** [comment]
Then if you haven't started this I can take it up after we finalise this discussion.

**Comment by Patowhiz** [comment]
Oh! I just saw the point. Samuel says up to the previous day. So I presume that means a user should not be able to save records of today.

**Comment by maxwellfundi** [comment]
yes, up to the previous day.

**Comment by maxwellfundi** [comment]
Okay.

**Comment by Patowhiz** [comment]
@maxwellfundi David suggested we do this at the base control level.
