### ISSUE TITLE
Back Colour for Text Boxes When Adding/Updating New Record

### ISSUE THREAD

**Issue by Patowhiz** [africanmathsinitiative/Climsoft#8]
@volloholic  suggested that the textbox background colour to be 
- white when it's a new record
- green when it's an existing value in the database
- orange when the value is an update of the original value
- red when it's an invalid value

This can be implement in the `UcrTextbox `control

**Comment by volloholic** [comment]
@maxwellfundi Can we take note of the colours that Samuel wants for this

**Comment by Patowhiz** [comment]
@maxwellfundi  what are Samuel colour preferences ? are they similar to what I've mentioned above?

**Comment by maxwellfundi** [comment]
@Patowhiz  we want red for critical errors, and white for  the new record

**Comment by maxwellfundi** [comment]
And cyan for non critical errors. Interestingly, when there is a missing value in the value textbox, its red but then when you put something else in, it does not change the color to white.

**Comment by Patowhiz** [comment]
This was fixed. We adopted samuel's colours.
